### ISSUE TITLE
Fallan los picons de Canal 13 y MTV España

### ISSUE THREAD

**Issue by ElBielas** [OpenLD/Astra19.2-Movistar-Transparent#1]
Hola, lo primero gracias por tus picons !!! Estan geniales, todos bien excepto el de Calle 13 HD y MTV España, no los muestra, no se si estara mal el nombre del picon.

Gracias

**Comment by javilonas** [comment]
¿Qué lista de canales tienes puesta? me da la impresión de que ese listado no tiene los canales actuales con las referencias que le corresponde a esos dos canales.

Te dejo una captura del listado que trae OpenLD 3.2 y estos picons que tú comentas:

![1_0_19_7857_41a_1_c00000_0_0_0_20180513164953](https://user-images.githubusercontent.com/2302257/39968493-dca41056-56cd-11e8-91e0-a523b0d0ca23.jpg)

**Comment by meliosolo** [comment]
Si me aceptas un consejo, no uses las listas de sorys. Si quieres, puedes usarla como base para los bouquets de las compañías extranjeras, pero si sólo te interesa la de España, no te hacen falta las listas de sorys para nada.

Haz una búsqueda ciega en el deco, y dile que borre antes de buscar, así te borrará las frecuencias viejas y los fallos que tenga la lista de sorys. Estos dos picons y todos los demás deben de funcionarte bien.

**Comment by ElBielas** [comment]
Las uso para que me salgan ordenados los canales y dividirlos por temática, si no me tocaría ordenarlos a mano y son unos pocos.... Siempre que hago búsqueda pongo que borre los actuales. Solo uso canales de españa, mi antena es comunitaria, alguna forma/truco para que salgan ordenados, después de la busqueda ?
