### ISSUE TITLE
Faltan bastantes de Movistar en HD

### ISSUE THREAD

**Issue by jlazkano** [OpenLD/Astra19.2-Movistar-Transparent#2]
Hola,

Lo primero agradecerte tu trabajo, pero quería preguntar si tenéis intención de subir los de Movistar en HD.

Como Accion HD, DCine HD...

Gracias y un saludo.

**Comment by javilonas** [comment]
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180630235442](https://user-images.githubusercontent.com/2302257/42129282-fbf3c686-7cc0-11e8-983e-b0f4c955dc81.jpg)

¿Cuales son los que dices que faltan? Acción HD y Dcine ya están... @meliosolo ¿Tú ves que falte alguno?

**Comment by javilonas** [comment]
Me he descargado los cambios últimos ya que me faltaba el de LTC, pero el resto me siguen saliendo sin problemas.

**Comment by javilonas** [comment]
Te añado un previa del listado completo + un extra del infobar con el acción HD:

![1_0_19_74d5_3f8_1_c00000_0_0_0_20180630235827](https://user-images.githubusercontent.com/2302257/42129462-8d2b5002-7cc5-11e8-986a-bb0887776f8e.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002522](https://user-images.githubusercontent.com/2302257/42129463-94ee371e-7cc5-11e8-9222-94381f60bc8f.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002530](https://user-images.githubusercontent.com/2302257/42129464-95075e42-7cc5-11e8-9400-eb02dee990cd.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002541](https://user-images.githubusercontent.com/2302257/42129465-951fec46-7cc5-11e8-8efd-4d8474a6b660.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002552](https://user-images.githubusercontent.com/2302257/42129466-9537391e-7cc5-11e8-9231-836601838fc3.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002559](https://user-images.githubusercontent.com/2302257/42129467-954fb746-7cc5-11e8-9a59-90640ece9e3a.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002608](https://user-images.githubusercontent.com/2302257/42129468-9568cd08-7cc5-11e8-9666-7442cbf49e9c.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002615](https://user-images.githubusercontent.com/2302257/42129469-95824710-7cc5-11e8-8961-6bba30f21f64.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002622](https://user-images.githubusercontent.com/2302257/42129470-959b3004-7cc5-11e8-97ad-0de985ac7124.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002630](https://user-images.githubusercontent.com/2302257/42129471-95c573a0-7cc5-11e8-9f5b-d47bf882c5a3.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002638](https://user-images.githubusercontent.com/2302257/42129472-95e44488-7cc5-11e8-9c73-b4dd23fd5e69.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002644](https://user-images.githubusercontent.com/2302257/42129473-95fdad24-7cc5-11e8-8783-f13793351ac3.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002650](https://user-images.githubusercontent.com/2302257/42129474-96176b60-7cc5-11e8-8aa6-649990deffa6.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002702](https://user-images.githubusercontent.com/2302257/42129475-96345720-7cc5-11e8-8b7c-2e3584548c11.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002455](https://user-images.githubusercontent.com/2302257/42129476-96794b46-7cc5-11e8-9adc-bad785b04b49.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002506](https://user-images.githubusercontent.com/2302257/42129477-9694752e-7cc5-11e8-9cb1-c003b3fd3068.jpg)
![1_0_19_74d5_3f8_1_c00000_0_0_0_20180701002515](https://user-images.githubusercontent.com/2302257/42129478-96d320bc-7cc5-11e8-88be-3556449e4995.jpg)

PD: el orden de las fotos es el que github ha decidido :(

**Comment by meliosolo** [comment]
El listado está completo, haz una búsqueda nueva de canales o bájate una lista actualizada y te saldrán todos. A menos que Movistar haya hecho cambios en la última semana.

**Comment by jlazkano** [comment]
Buenos dias,

Me refiero a que en algunos iconos aparece la palabra "HD" como en Cosmo: https://github.com/OpenLD/Astra19.2-Movistar-Transparent/blob/master/1_0_19_78B8_3EC_1_C00000_0_0_0.png

Y en las de Movistar, como Estrenos por ejemplo, no aparece la palabra "HD": https://github.com/OpenLD/Astra19.2-Movistar-Transparent/blob/master/1_0_1_76C0_40E_1_C00000_0_0_0.png

Gracias por todo.

Un saludo.

**Comment by meliosolo** [comment]
Los picons están hechos como salen en pantalla, los picons que muestra Movistar en sus canales propios no indican que sean HD o no, por eso mis picons tampoco tienen puesto el HD.

**Comment by jlazkano** [comment]
OK, entendido, pues se puede cerrar este hilo.

Siento las molestias y gracias por la ayuda.

Un saludo.
