### ISSUE TITLE
Picos Movistar+ Satelite Astra tamaño 440x264

### ISSUE THREAD

**Issue by JUANLUK** [OpenLD/Astra19.2-Movistar-Transparent#3]
hola

por favor, podrias actualizar los picons 440x264 y no solo 220x132?
son los mejores picons y me faltan los últimos de 440.

muchas gracias

**Comment by meliosolo** [comment]
Lo siento, sólo hago picons en 132p. No le veo sentido hacerlos en 236p cuando el deco los reescala.
